### ISSUE TITLE
Document conventions

### ISSUE THREAD

**Issue by nmint8m** [cleapp/ios-basic-training#2]
Discuss the convention that is used for the whole document.

**Comment by nmint8m** [comment]
I think we should do:
- [ ] Uppercase the first letter of commits
- [ ] Do similarly with olders' name and files' name
- [ ] We don't really need to resize images, we can use these in markdown files:
```
<img src="..." width="" heigh="">
<img src="..." width=">
<img src="..." heigh="">
```
@suho Do you agree with me?

**Comment by suho** [comment]
1. Why we need to uppercase the first letter of commits?
2. Why?
3. Ok, I will use **img** tag when to resize the image.

**Comment by nmint8m** [comment]
1. The `Initial commit` is the default commit that Github create. I want to keep that format till the end.
2. Default name of folders and files when creating new project was uppercased the first letter. For example, folder `Assets.xcassets` or file `Info.plist`. So I want to keep that format till the end.
3. Thank you.

**Comment by suho** [comment]
Got it 💯
