### ISSUE TITLE
Markdown Style Guide - How to emphasize a word?

### ISSUE THREAD

**Issue by suho** [cleapp/ios-basic-training#4]
In Markdown, we have some ways to emphasize a word, today we will discuss how to use it. Thus, I think:
- With `[code]`, it only for code, so when we use swift code or name of a class or everything relative to the syntax of any programming languages please use `[code]`.
- About _italic_ or **bold**, when you type something on Github, you press (cmd+b) it will show ** for bold, and (cmd+i) will show _ for italic. So if you want to use style italic or bold, please use ** for bold and _ for italic.
- According to this article: https://practicaltypography.com/bold-or-italic.html, because of the font of *GitHub*, I think *italic* must not use for emphasizing the word, because it does not look quite different when italicized. 
Conclusion, use `code` for anything relative to programming languages, and **bold** for the words you want to emphasize

How about you?

**Comment by suho** [comment]
@nmint8m please give me some suggestions, I need your 🧠

**Comment by suho** [comment]
@nmint8m Any suggestions?

**Comment by nmint8m** [comment]
I agree with you, so from now on, we will use:
- `[code]` for code and things related to programming
- ** for bold
- _ for italic
Beside I don't really want we use italic font too much in documentations, just in case it is really neccessary.
Please close this issue! @suho
